### ISSUE TITLE
Duplicate entries in DiMe

### ISSUE THREAD

**Issue by jmakoske** [HIIT/dime-webextension#4]
For example, after filing the previous issue, these appeared in my DiMe:
![screen shot 2016-06-22 at 13 55 09](https://cloud.githubusercontent.com/assets/12252082/16264259/2ac4f4c0-3881-11e6-9fd5-f23287bb0348.png)

**Comment by chenhunghan** [comment]
Did you refresh the page? If so, duplicate entries should be recorded (with different timestamp)

**Comment by jmakoske** [comment]
I don't think I refreshed the page, definitely not that many times as in the screenshot. Also, there are two sets of three events with the same timestamp in the screenshot.

**Comment by chenhunghan** [comment]
ok. let me see if I could find the problem...

**Comment by chenhunghan** [comment]
This happens because of a strange behavior of Chrome API (chrome.tabs.update). The chrome.tabs.update event will fire twice [with status="compete" if there is an iframe on the page](http://stackoverflow.com/questions/36808309/chrome-extension-page-update-twice-then-removed-on-youtube). I have added a hack to avoid this. It should be fixed in latest commit. Please help me to confirm.
