### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by mvsjober** [HIIT/dime-webextension#6]
A Firefox version might be possible now when there is partial support for the Chrome web extensions API in recent versions of Firefox.

**Comment by chenhunghan** [comment]
Since this commit https://github.com/HIIT/dime-webextension/commit/360dbc33c4899b7b22eef5a16fc7e5f6a83b5912 size of background.js has been significantly reduced (by separating original dime.bakcground.js (over 4MB) into 11 single JavaScript files.). Firefox support should be possible (see introduction here: [Distribute as Firefox Add-on](https://github.com/HIIT/dime-webextension)) .
